# Generated by Django 5.0 on 2023-12-30 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', 'init_value_for_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Branch',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agencyapp.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='group_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='agencyapp.group'),
        ),
        migrations.AlterField(
            model_name='user',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapp.branch')),
                ('manager_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserGroup',
        ),
    ]
