# Generated by Django 5.0 on 2023-12-30 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0004_alter_branch_branch_name_alter_group_group_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_description', models.CharField(max_length=300)),
                ('product_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapp.branch')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapp.product')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(max_length=30)),
                ('service_rate', models.IntegerField()),
                ('service_description', models.CharField(max_length=300)),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapp.branch')),
            ],
        ),
    ]
