# Generated by Django 5.0 on 2023-12-30 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0007_alter_product_product_rate_alter_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_qty', models.IntegerField()),
                ('payment_status', models.CharField(choices=[('P', 'Pending'), ('D', 'Delivered'), ('C', 'Cancelled')], max_length=30)),
                ('delivery_status', models.CharField(choices=[('P', 'Pending'), ('S', 'Success')], max_length=30)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapp.product')),
                ('service_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencyapp.service')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
