# Generated by Django 5.0 on 2023-12-30 16:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0008_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='delivery_status',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='payment_status',
            field=models.CharField(max_length=30),
        ),
    ]
