# Generated by Django 5.0 on 2024-01-01 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0009_bookings_date_alter_bookings_delivery_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='booking_type',
            field=models.CharField(default='PRODUCT', max_length=30),
        ),
        migrations.AddField(
            model_name='bookings',
            name='cost',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='product_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agencyapp.product'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='product_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(max_length=30)),
                ('work_assign_date', models.DateTimeField(auto_now_add=True)),
                ('work_complete_date', models.DateTimeField()),
                ('booking_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencyapp.bookings')),
                ('staff_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
