# Generated by Django 5.0 on 2024-01-01 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0010_bookings_booking_type_bookings_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookings',
            old_name='date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='work',
            old_name='work_assign_date',
            new_name='created_at',
        ),
    ]
