# Generated by Django 5.0 on 2024-01-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0011_rename_date_bookings_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='work_status',
            field=models.CharField(default='PENDING', max_length=30),
            preserve_default=False,
        ),
    ]
