# Generated by Django 5.0 on 2024-01-01 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0012_work_work_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='work_assigned',
            field=models.BooleanField(default=False),
        ),
    ]
