# Generated by Django 5.0 on 2024-01-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0013_bookings_work_assigned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='work_name',
        ),
        migrations.AlterField(
            model_name='work',
            name='work_status',
            field=models.CharField(default='ASSIGNED', max_length=30),
        ),
    ]
