# Generated by Django 5.0 on 2024-01-01 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0014_remove_work_work_name_alter_work_work_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='work_complete_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
