# Generated by Django 5.0 on 2024-01-01 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0015_alter_work_work_complete_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='branch_id',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='agencyapp.branch'),
            preserve_default=False,
        ),
    ]
