# Generated by Django 5.0 on 2024-01-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencyapp', '0020_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='read',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
